#!/usr/bin/env bash
set -o errexit

DOMAIN=${1:-magento.test}
VERSION=${2:-2.4.7}
EDITION=${3:-community}

if [ -d "./bin" ]; then
  echo "Error: The current directory is not empty. Please remove all contents within this directory and try again."
  exit 1
fi

curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/template | bash

# &&'s are used below otherwise onelinesetup script fails/errors after bin/download
bin/download "${VERSION}" "${EDITION}" \
  && bin/setup "${DOMAIN}"
