#!/bin/bash
PROJECT_DIRECTORY=${1:-magento2}

mkdir "$PROJECT_DIRECTORY"
cd "$PROJECT_DIRECTORY" || exit

git init -qqq
git remote add origin https://github.com/rossbrandon/docker-magento
git fetch origin -qqq
git checkout origin/master -- compose
mv compose/* ./
mv compose/.vscode ./
rm -rf compose .git
git init
