services:
  app:
    volumes: &appvolumes
      - ./src/nginx.conf.sample:/var/www/html/nginx.conf:cached
      - ./src:/var/www/html:cached

  phpfpm:
    volumes: *appvolumes    
    
  phpmyadmin:
    image: linuxserver/phpmyadmin
    environment:
      - password: rootuser
      - phpadmin_password: pass@1234
    ports:
      - "8088:80"
    depends_on:
      - db
